---
Name: collectors
---

ArtworksAdmin:
  extensions:
    - SubsiteMenuExtension

CollectorsAdmin:
  extensions:
    - SubsiteMenuExtension

DocumentsAdmin:
  extensions:
    - SubsiteMenuExtension
    
ArticlesAdmin:
  extensions:
    - SubsiteMenuExtension
