---
Name: collectors
---

ArchivesAdmin:
  extensions:
    - SubsiteMenuExtension

CollectorsAdmin:
  extensions:
    - SubsiteMenuExtension
      
Person:
  extensions:
    - DataObject_MemberExtension
